"""Tests for the online BCI simulation modules."""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pytest

from src.online.classifier import OnlineClassifier, LABEL_MAP
from src.online.replay import ReplayStream

ROOT = Path(__file__).resolve().parent.parent

# Paths to FBCSP+SVM sub1 artefacts (generated by train.py)
MODELS_DIR = ROOT / "results" / "fbcsp_svm_2a" / "models"
MODEL_PATH = MODELS_DIR / "fbcsp_svm_2a_sub1.pkl"
EXTRACTOR_PATH = MODELS_DIR / "fbcsp_svm_2a_sub1_extractor.pkl"
REPLAY_PATH = MODELS_DIR / "replay_data_sub1.npz"

needs_model = pytest.mark.skipif(
    not MODEL_PATH.exists(), reason="Trained model not found — run train.py first"
)
needs_replay = pytest.mark.skipif(
    not REPLAY_PATH.exists(), reason="Replay data not found — run train.py first"
)


# ---------------------------------------------------------------------------
# Test ReplayStream
# ---------------------------------------------------------------------------

class TestReplayStream:
    @needs_replay
    def test_load_and_iterate(self):
        stream = ReplayStream(REPLAY_PATH, shuffle=False, loop=False)
        assert len(stream) > 0

        trials = list(stream)
        assert len(trials) == len(stream)

        epoch, label = trials[0]
        assert epoch.ndim == 3  # (1, n_ch, n_times)
        assert epoch.shape[0] == 1
        assert label in LABEL_MAP

    @needs_replay
    def test_loop(self):
        stream = ReplayStream(REPLAY_PATH, shuffle=False, loop=True)
        count = 0
        for epoch, label in stream:
            count += 1
            if count >= len(stream) + 5:
                break
        assert count == len(stream) + 5  # looped past end

    def test_infer_path(self):
        inferred = ReplayStream.infer_path(MODEL_PATH)
        if REPLAY_PATH.exists():
            assert inferred == REPLAY_PATH
        else:
            # If model doesn't exist, infer should return None
            pass


# ---------------------------------------------------------------------------
# Test OnlineClassifier
# ---------------------------------------------------------------------------

class TestOnlineClassifier:
    @needs_model
    def test_load_and_predict(self):
        clf = OnlineClassifier(MODEL_PATH, EXTRACTOR_PATH)
        assert clf.model is not None
        assert clf.extractor is not None

        # Load one trial from replay data
        data = np.load(REPLAY_PATH)
        epoch = data["X"][0:1]  # (1, n_ch, n_times)

        result = clf.predict_trial(epoch)
        assert "label" in result
        assert "confidence" in result
        assert "latency_ms" in result
        assert result["label"] in LABEL_MAP
        assert 0 <= result["confidence"] <= 1
        assert result["latency_ms"] >= 0

    @needs_model
    def test_predict_2d_input(self):
        """Should accept (n_ch, n_times) without batch dim."""
        clf = OnlineClassifier(MODEL_PATH, EXTRACTOR_PATH)
        data = np.load(REPLAY_PATH)
        epoch = data["X"][0]  # (n_ch, n_times) — no batch dim

        result = clf.predict_trial(epoch)
        assert result["label"] in LABEL_MAP

    @needs_model
    def test_infer_extractor_path(self):
        inferred = OnlineClassifier.infer_extractor_path(MODEL_PATH)
        assert inferred is not None
        assert inferred == EXTRACTOR_PATH

    @needs_model
    def test_without_extractor(self):
        """Should work without extractor (e.g. EEGNet)."""
        clf = OnlineClassifier(MODEL_PATH, extractor_path=None)
        assert clf.extractor is None


# ---------------------------------------------------------------------------
# Test WebSocket server (unit-level, no actual network)
# ---------------------------------------------------------------------------

class TestBCIServer:
    @needs_model
    @needs_replay
    def test_server_construction(self):
        from src.online.server import BCIServer

        clf = OnlineClassifier(MODEL_PATH, EXTRACTOR_PATH)
        replay = ReplayStream(REPLAY_PATH, loop=False)
        server = BCIServer(clf, replay, port=0)  # port=0 just for construction
        assert server.classifier is clf
        assert server.replay is replay
